#!/bin/bash
# usage: ./run 'grammar' 'rewrite' 'support' 'src'
# (supply a library directory, a grammar file, a rewrite file, and a support (JS) file, inhale a source file (written in new nDSL syntax), exhale output of running the nanoDSL code
set -e
LIB=$1
GRAMMAR=$2
REWRITE=$3
SUPPORT=$4
SRC=$5
node ${LIB}/t2t.mjs ${REWRITE} >temp.rewrite.mjs
cat ${LIB}/front.part.js ${GRAMMAR} ${LIB}/middle.part.js ${LIB}/args.part.js ${SUPPORT} temp.rewrite.mjs ${LIB}/tail.part.js >temp.nanodsl.mjs
node temp.nanodsl.mjs ${SRC}
